### ISSUE TITLE
Allow to add multiple tools with one add function call.

### ISSUE THREAD

**Issue by kineticwallet** [rojo-rbx/rokit#54]
Adding support like npm/yarn/pnpm allows you to do `pnpm add @a/b @c/d @e/f` for installing tools would improve the DX a lot.

Example:
![image](https://github.com/user-attachments/assets/3060ecb9-8e6b-413b-913a-50e43ad01705)

**Comment by filiptibell** [comment]
Currently the command allows two arguments, with the second one being for changing the "alias":

```sh
rokit add rojo-rbx/rojo@7.4.1 rojo7
rokit add rojo-rbx/rojo@6.0.0 rojo6
rokit install
```

Adding rojo with aliases like this means you can now run these different versions of rojo at the same time:

```sh
rojo7 --version # prints 7.4.1
rojo6 --version # prints 6.0.0
```

All this to say, there already exists a multi-argument variant of this command, and unfortunately it would be both a breaking change and we would be removing the ability to change the alias of a tool. I don't think we will do this unless it turns out that the community does not really care for the aliases functionality.
